### ISSUE TITLE
Dependencies uncooperative

### ISSUE THREAD

**Issue by chipbuster** [stevemclaugh/link-juicer#1]
Upon attempting to install the dependencies listed in the README, I encountered the following:

```
Error: pyqt was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!
```

In addition, it doesn't seem to play well with newer versions of Python (e.g. for Python 3.6, there doesn't appear to be a compatible version of pyqt4 in the PyPI repos), and Anaconda doesn't show any packages available for the most recent Python version.

In essence, there appear to be a lot of problems with PyQt4, and I doubt they're going to get much better moving forward. Unless there's something in that package that's critical to the functionality of the program (which I didn't see, but I only did a very quick scan), it might be worth trying to replace it.

**Comment by stevemclaugh** [comment]
Thanks, much appreciated. It looks like PhantomJS no longer requires Qt, so I'll run some tests and update the docs.
http://phantomjs.org/download.html
